name: India Market Morning Brief

on:
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  send-market-brief:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run market brief script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python main.py
